vexxhost/magnum-cluster-api

magnum_cluster_api/driver.py
magnum_cluster_api/resources.py

Add support for boot_volume_{size,type}

---

magnum_cluster_api/utils.py

It requires lowercase bool-like string

fix: Fix tls-insecure of ccm configuration

---

magnum_cluster_api/resources.py

fix for issue https://github.com/vexxhost/magnum-cluster-api/issues/70

fix: add label calico_ipv4_pool

---

magnum_cluster_api/resources.py

- Raise exception when the cert_ref is none in get_object
- Delete the k8s secret using its metadata only
fix #132

fix: Fix the certificate deletion

---

magnum_cluster_api/driver.py
magnum_cluster_api/exceptions.py
magnum_cluster_api/utils.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/116

feat: Allow odd number of master count only

---

magnum_cluster_api/driver.py
magnum_cluster_api/objects.py
magnum_cluster_api/resources.py
magnum_cluster_api/utils.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/64

feat: Expose underlying k8s resource status to coe cluster status reason

---

magnum_cluster_api/helm.py
magnum_cluster_api/tests/unit/test_helm.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/137

fix: Do not upgrade helmrelease in pending status

---

.github/workflows/image.yml
.github/workflows/test.yml
docs/admin/troubleshooting.md

- doc: add details for deleted projects
- ci: don't run ci for doc changes

docs: add deleted project docs

---

docs/user/getting-started.md
magnum_cluster_api/resources.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/164

feat: Add labels for nodegroup name and role name

---

magnum_cluster_api/driver.py
magnum_cluster_api/exceptions.py
magnum_cluster_api/utils.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/165

feat: Validate flavors

---

docs/admin/troubleshooting.md

Amend file `troubleshooting.md` on Line 71, it has `descrube` instead of `describe`. Therefore, it will facilitae the COPY and PASTE of the command during troubleshooting.

Amend troubleshooting.md

---

magnum_cluster_api/resources.py

feat: enable in-cluster traffic

---

README.md
docs/user/configs.md

drive-by: Add doc site link in the readme
fix https://github.com/vexxhost/magnum-cluster-api/issues/205

chore: Add configuration options in the doc

---

hack/stack.sh

Closes https://github.com/vexxhost/magnum-cluster-api/issues/199

ci: make capi+capo version configurable

---

magnum_cluster_api/monitor.py

fix: use capi to determine health

---

magnum_cluster_api/resources.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/200

chore: Rename volume types more properly

---

magnum_cluster_api/resources.py
magnum_cluster_api/tests/unit/test_resources.py
magnum_cluster_api/utils.py

Support image name in CAPI

---

magnum_cluster_api/resources.py

fix: Set nodegroup labels always

---

magnum_cluster_api/resources.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/259

fix: set nodeVolumeDetachTimeout property for machines

---

hack/run-functional-tests.sh
magnum_cluster_api/resources.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/256

fix: fix cluster initialization error for audit log enabled clusters

---

hack/stack.sh

Enable Magnum UI in the devstack installation.

hack/stack.sh: Install magnum-ui.

---

magnum_cluster_api/privsep/haproxy.py
magnum_cluster_api/proxy/manager.py
magnum_cluster_api/proxy/templates/haproxy.cfg.j2
magnum_cluster_api/proxy/utils.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/222

chore: Use home path for haproxy pid file

---

magnum_cluster_api/driver.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/308

fix: deploy autoscaler right before the cluster creation completed

---

docs/admin/intro.md
docs/user/getting-started.md

fix: https://github.com/vexxhost/magnum-cluster-api/issues/310

Add blog references

---

magnum_cluster_api/resources.py

fix: respect `availability_zone` for control plane

---

magnum_cluster_api/cmd/image_builder.py
magnum_cluster_api/cmd/image_loader.py
magnum_cluster_api/proxy/manager.py
magnum_cluster_api/resources.py

fix an incorrect jsonpatch introduced by [this](https://github.com/vexxhost/magnum-cluster-api/commit/113de308b465e659d25c2d19741449a8f3d1489e#diff-43c5da84e3410f51531d7b4f6bdfe0b0f83fe9a19018cf1dde7ee2ef352bb019R1373-R1377) 
Closes #330

fix: fix jsonpatch for preKubeadmCommands

---

docs/user/labels.md
magnum_cluster_api/tests/unit/test_utils.py
magnum_cluster_api/utils.py

Closes #347
- **add unit tests for ccm config**
- **feat: allow ovn lbs**

feat: allow ovn lbs

---

magnum_cluster_api/objects.py

fix: use get method to get obj component

---

magnum_cluster_api/driver.py

In the psat, if we get a cluster upgrade request when the kube_tag
did not change, we did not actually mutate the state of the cluster.
However, there is an expectation that an upgrade operation will
mutate the state of the cluster, so we will always apply the resources
when we see an upgrade come in.
Closes #381

fix: force a cluster upgrade all the time

---

magnum_cluster_api/driver.py
magnum_cluster_api/json_patches.py
magnum_cluster_api/objects.py
magnum_cluster_api/resources.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/4

feat: support docker volume type and size

---

magnum_cluster_api/resources.py

Run configure-kube-proxy.sh

---

magnum_cluster_api/proxy/structs.py

In our environment, the k8s control plane cluster does not have Internet access. As such, even when a workload cluster uses a floating IP we need to make use of the proxy service to ensure the control plane cluster can reach the workload.
This PR adds an environment variable, matching existing patterns, to provide a way for deployments to always proxy access to the workload clusters.
This also adds a check that the load balancer internalIP exists as a cluster without a load balancer would cause the IP in the HAProxy config to be rendered as `None`

feat: add env var so proxy can work when floating IPs are in use

---

magnum_cluster_api/tests/unit/test_utils.py

A regression to linters tests was introduced in #456 and this is a
follow-up to cover it.

Fix line length linters issue

---

docs/user/labels.md
hack/stack.sh
magnum_cluster_api/cache.py
magnum_cluster_api/driver.py
magnum_cluster_api/resources.py
magnum_cluster_api/tests/conftest.py
magnum_cluster_api/tests/unit/test_driver.py
magnum_cluster_api/utils.py

requires https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2163 for 0.10 capo
Closes: #375

[MCAPI-45] feat: introduce sever groups

---

Cargo.lock
Cargo.toml
crates/helm/Cargo.toml
crates/helm/src/lib.rs
magnum_cluster_api/charts/k8s-keystone-auth/templates/configmap-policy.yaml
magnum_cluster_api/charts/k8s-keystone-auth/templates/configmap-sync.yaml
magnum_cluster_api/charts/k8s-keystone-auth/templates/daemonset.yaml
magnum_cluster_api/charts/k8s-keystone-auth/templates/secret-ca.yaml
magnum_cluster_api/charts/k8s-keystone-auth/templates/service.yaml
magnum_cluster_api/charts/k8s-keystone-auth/templates/serviceaccount.yaml
magnum_cluster_api/resources.py
src/addons/cilium.rs
src/addons/mod.rs
src/lib.rs
src/magnum.rs
src/models.rs
src/resources.rs
uv.lock
zuul.d/playbooks/cargo/test.yml

- **Initial Cilium feature**
- **Transition Cilium as Rust addon**

add cilium as addon

---

magnum_cluster_api/utils.py

Closes: https://github.com/vexxhost/magnum-cluster-api/issues/483

fix: replace $PROJECT_ID in the template

---

magnum_cluster_api/resources.py
magnum_cluster_api/tests/functional/test_resources.py
magnum_cluster_api/tests/unit/test_driver.py
magnum_cluster_api/tests/unit/test_resources.py
magnum_cluster_api/utils.py
src/features/test.rs
src/features/volumes.rs
src/resources.rs

- **Remvoe extra patch print**
- **Update feature to support hardwareSCSIModel**
- **Add python variables side**
- **Fix tests**

feat: support virtio-scsi model

---

.github/workflows/ci.yml
devstack/local.conf.sample
hack/stack.sh
zuul.d/jobs.yaml
zuul.d/project.yaml

- until this issue is fixed, disable uwsgi in manila https://bugs.launchpad.net/manila/+bug/2109645
- https://review.opendev.org/c/openstack/magnum/+/949110

ci: fix devstack installation

---

src/features/mod.rs

enable traffic from anywhere to node port services on all nodes

---

flake.nix
src/addons/cilium.rs
src/addons/cloud_controller_manager.rs
src/addons/mod.rs
src/driver.rs
src/features/api_server_load_balancer.rs
src/features/cluster_identity.rs
src/features/containerd_config.rs
src/features/control_plane_availability_zones.rs
src/features/disable_api_server_floating_ip.rs
src/features/external_network.rs
src/features/flavors.rs
src/features/image_repository.rs
src/features/images.rs
src/features/mod.rs
src/features/openid_connect.rs
src/features/operating_system.rs
src/features/ssh_key.rs
src/features/tls.rs
src/magnum.rs
src/resources.rs

- **chore: add generics**
- **chore: avoid constant rebuilds**
- **chore: cargo fmt**

chore: refactor + cleanups

---

.github/workflows/ci.yml

https://github.com/kubernetes/cloud-provider-openstack/issues/2884

ci: create volumev3 service and endpoint

---

.github/workflows/ci.yml
pyproject.toml
uv.lock

Signed-off-by: Mohammed Naser <mnaser@vexxhost.com>

Drop older than Python 3.10

---

Cargo.lock
Cargo.toml
pyproject.toml
src/addons/cilium.rs
src/addons/cinder_csi.rs
src/addons/cloud_controller_manager.rs
src/addons/manila_csi.rs
src/magnum.rs

- **chore: enable Default for cluster**
- **chore: add status field to Magnum object**

add status handling
