magnum_cluster_api/resources.py

i missed test https://github.com/vexxhost/magnum-cluster-api/pull/23.
This is the fix after test

Fix ge_or_none usage in cluster delete

---

magnum_cluster_api/resources.py

Now get_object method has an assert. Once this assertion is negative, deletion is failed as well as creation. By overriding the deletion method using the config map name directly, it avoids deletion failure. Also, it will reduce API requests.

Override delete method of ClusterResourcesConfigMap

---

magnum_cluster_api/driver.py
magnum_cluster_api/utils.py

CloudConfigSecret is used to generate the configuration of ccm which will be deployed on coe clusters.
Internal auth_url is not resolvable inside coe clusters. This PR uses public auth_url.
In addition, add `tls_insecure` field in ccm config to support self-signed certs

fix: Use public auth_url for CloudConfigSecret

---

.markdownlint.rb
.mdlrc
magnum_cluster_api/cmd/image_loader.py
magnum_cluster_api/image_utils.py
magnum_cluster_api/utils.py
pyproject.toml

In addition, disable MD012 (Multiple consecutive blank lines) mdl lint rule.
This is annoying us against CHANGELOG.md file which is generated by release-please process.

feat: Use crane for image loader instead of skopeo

---

hack/stack.sh

includes https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1493
fix https://github.com/vexxhost/magnum-cluster-api/issues/72

chore: Update CAPO version to 0.7.1

---

pyproject.toml

Explicitly declaring charts dir in include to negate .gitignore

fix: Add missing autoscaler chart manifests

---

.github/workflows/test.yml
docs/labels.md
magnum_cluster_api/cmd/proxy.py
magnum_cluster_api/driver.py
magnum_cluster_api/monitor.py
magnum_cluster_api/objects.py
magnum_cluster_api/privsep/__init__.py
magnum_cluster_api/privsep/haproxy.py
magnum_cluster_api/proxy/manager.py
magnum_cluster_api/proxy/structs.py
magnum_cluster_api/proxy/templates/haproxy.cfg.j2
magnum_cluster_api/proxy/utils.py
magnum_cluster_api/resources.py
magnum_cluster_api/service.py
magnum_cluster_api/utils.py
poetry.lock
pyproject.toml

This PR adds a new component, the `magnum-cluster-api-proxy` which should run on DHCP nodes.  It will start up an instance of HAproxy accessible within the management cluster which will proxy traffic directly into the cluster.
This allows deploying Kuberentes clusters inside isolated networks that the CAPI cannot reach directly over this proxy.

feat: add m-capi-proxy

---

magnum_cluster_api/driver.py

fix: Skip delete_cluster when stack_id is none

---

docs/user/labels.md
magnum_cluster_api/resources.py

fix https://github.com/vexxhost/magnum-cluster-api/issues/119

feat: Support OpenID Connect for kube-api auth

---

hack/stack.sh

This is primarily driven in order to allow for making changes to autoscaling configurations without causing a full rollout.

fix: bump capi

---

magnum_cluster_api/driver.py
magnum_cluster_api/resources.py

chore: Drop MachineDeployment annotation workaround

---

magnum_cluster_api/driver.py
magnum_cluster_api/helm.py
magnum_cluster_api/resources.py
magnum_cluster_api/tests/unit/test_helm.py

- fix(helm): make upgrades more robust
- fix(helm): skip deploying autoscaler unnecessarily

fix(helm): make autoscaler deploys more robust

---

magnum_cluster_api/resources.py

With a low maxUnhealthy of 33%, it is possible that a small cluster
with a single node failure will not actually trigger a failover
when in a 3 node cluster.

fix(mhc): increase max unhealthy to 80%

---

docs/user/getting-started.md

Current doc about the nodegroup role is not enough to understand for users who are expecting the old labels like `magnum.openstack.org/role`.
More verbose description added.

chore: Update user doc related to nodegroup roles

---

.github/workflows/test.yml
CHANGELOG.md
README.md
docs/developer/testing-and-development.md
docs/user/getting-started.md
hack/run-functional-tests.sh
hack/stack.sh
magnum_cluster_api/cmd/image_builder.py
magnum_cluster_api/driver.py
magnum_cluster_api/resources.py
magnum_cluster_api/utils.py
pyproject.toml

Based on: https://github.com/vexxhost/magnum-cluster-api/pull/44
Adapted the aforementioned PR to contain the right ignition config and also modified the secret type used for the CA cert secret.
CAPI expects a CA secret of type "cluster.x-k8s.io/secret" instead of "kubernetes.io/tls". Also, the "cluster.x-k8s.io/cluster-name" label has been added for the secret resource, containing the cluster's stack id.

feat: Support Flatcar OS

---

docs/user/configs.md
hack/stack.sh
magnum_cluster_api/conf.py
magnum_cluster_api/driver.py
magnum_cluster_api/resources.py
magnum_cluster_api/utils.py

feat: Support endpoint configuration for cluster-api

---

magnum_cluster_api/driver.py

2023-10-10 04:06:21.169 7 ERROR oslo.service.loopingcall [-] Fixed interval looping call 'magnum.service.periodic.ClusterUpdateJob.update_status' failed: TypeError: __init__() missing 1 required positional argument: 'cluster' 2023-10-10 04:06:21.169 7 ERROR oslo.service.loopingcall Traceback (most recent call last):
2023-10-10 04:06:21.169 7 ERROR oslo.service.loopingcall   File "/var/lib/kolla/venv/lib/python3.9/site-packages/oslo_service/loopingcall.py", line 150, in _run_loop
2023-10-10 04:06:21.169 7 ERROR oslo.service.loopingcall     result = func(*self.args, **self.kw)
2023-10-10 04:06:21.169 7 ERROR oslo.service.loopingcall   File "/var/lib/kolla/venv/lib/python3.9/site-packages/magnum/service/periodic.py", line 72, in update_status
2023-10-10 04:06:21.169 7 ERROR …

fix: Missed context argument in resources.CloudConfigSecret.delete() call

---

hack/run-functional-tests.sh
magnum_cluster_api/objects.py

chore: Migrate cluster api CRD version from v1alpha6 to v1alpha7

---

magnum_cluster_api/driver.py
magnum_cluster_api/utils.py

feat: Validate fixed_network and fixed_subnet existence

---

docs/user/labels.md
magnum_cluster_api/resources.py

This patch allows you to configure TLS cipher suites for the
API server with a sane set of secure defaults.
Closes #251

fix: allow configuring tls-cipher-suites

---

docs/user/labels.md
magnum_cluster_api/resources.py

relates to https://github.com/vexxhost/magnum-cluster-api/issues/251

feat: Support tls-cipher-suite configuration for kubelet

---

magnum_cluster_api/resources.py

Our testing against internal API endpoints has found that the use of 'interface' key in the clouds.yaml format doesn't appear to be working, but replacing this with 'endpoint_type' does. Whilst this is likely to be a bug in an underlying component, these appear to suggest that 'endpoint_type' is preferred, so there doesn't seem to be any harm in working around the issue here.
When looking into the underlying bug, we found https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/requests.go#L327, but it isn't clear whether the underlying issue is here or elsewhere.

chore: Use endpoint_type rather than interface to work around lib bug

---

magnum_cluster_api/proxy/utils.py

A host is not required to have a default gateway, more specific routes may be present instead.
In this situation get_default_gateway_interface() returns None, which is reasonable. get_default_ip_address() then fails with a struct pack error.
This patch allows get_default_ip_address to fall through and also return None when there is no interface identified as the default gateway.

Handle no default route in get_default_ip_address()

---

magnum_cluster_api/proxy/manager.py
magnum_cluster_api/proxy/utils.py

The proxy selects a random port by default but this causes difficulty in an environment where network traffic is controlled by a firewall, either host iptables or a physical appliance.
This patch adds an environment variable, PROXY_PORT, which allows the port to be pre-determined and made consistent.

feat: Add environment variable to set proxy port

---

magnum_cluster_api/resources.py

Change Cinder CSI Provisioner 
from
"provisioner": "kubernetes.io/cinder"
to
"provisioner": "cinder.csi.openstack.org",

Use up-to-date provisioner name for Cinder CSI

---

magnum_cluster_api/proxy/manager.py
magnum_cluster_api/proxy/templates/haproxy.cfg.j2

This patch adds the environment variable PROXY_BIND which can be optionally set to override the default that binds to "*".
Binding on all addresses may inadvertently expose the proxy service when run on a node that also has public interfaces such as a bare metal openstack infrastructure node, or a network node.

feat: Add environment variable to set proxy bind address

---

docs/developer/cluster-topology.md
flake.nix
magnum_cluster_api/driver.py
magnum_cluster_api/resources.py
magnum_cluster_api/tests/unit/conftest.py
magnum_cluster_api/tests/unit/test_driver.py
magnum_cluster_api/tests/unit/test_resources.py

When making any node group changes, we were previously
making an entire change of all the cluster resources.  With
this change, we're instead simply making the small changes
in the node group which should avoid unexpected full rollouts
of node groups when changing min/max for autoscaling or
resizing a cluster.

fix: stop unexpected rollouts

---

magnum_cluster_api/resources.py
magnum_cluster_api/utils.py

This PR adds support for HTTP proxy servers in user clusters, with config supplied via the existing Magnum proxy variables. Specifically, proxies are configured in containerd for image downloads, and in apt when running Ubuntu.
I've had to add a placeholder file to the KubeadmConfigTemplate as otherwise the JSON patch process fails when adding files to the empty array.

Add proxy config for containerd and apt on ubuntu

---

magnum_cluster_api/cmd/image_builder.py

Recent subiquity versions leave files in /etc/cloud/ that break networking when the images are booted in openstack.

Workaround k8s image-builder not handling recent subiquity installer

---

magnum_cluster_api/cmd/image_builder.py

These are needed to use the functions in image-builder to create an image with the nvidia GPU driver pre-installed.

Pass extra ansible_user_vars and node_custom_roles_pre to image-builder

---

magnum_cluster_api/cmd/image_loader.py
magnum_cluster_api/conf.py
magnum_cluster_api/image_utils.py
magnum_cluster_api/integrations/common.py
zuul.d/jobs-flatcar.yaml
zuul.d/jobs-rockylinux-8.yaml
zuul.d/jobs-rockylinux-9.yaml
zuul.d/jobs-ubuntu-2204.yaml
zuul.d/playbooks/sonobuoy/run.yml

@mnaser 
You can safely merge this - it will add only support for k8s 1.28.x
With k8s 1.28.x there is no issues with keystone auth

Kubernetes 1.28.x support

---

magnum_cluster_api/cmd/image_builder.py

This fixes issues #378 and #384 and allows the daily build ubuntu ISO to be used again to build images.

Update to image-builder 1.30

---

magnum_cluster_api/driver.py

Modified the condition to use OR instead of AND for skipping node groups. Now, node groups with a role of "master" or a status of "DELETE_COMPLETE" are skipped.
related to https://github.com/vexxhost/magnum-cluster-api/commit/0e904b6e256f6cfb5ddf32816707368ea6738ac2

fix: allow skipping node groups that are master or delete complete

---

magnum_cluster_api/resources.py

I may be misunderstanding, but as far as I can tell the keystone auth component lives entirely in a tenant's cluster, and so must always use the public endpoint to access Keystone.
As we change the capi_client endpoint_type to internal in our deployment, this appears to be contributing to a failure of the keystone auth components in tenant clusters.
If there was a way to get this component to use `/etc/kubernetes/cloud.conf` like other similar components I guess that would be preferable to having this separate definition.

keystone_auth: always use public endpoint from tenant cluster

---

hack/setup-capo.sh
magnum_cluster_api/resources.py

capi 1.6 -> 1.8.4
capo 0.9 -> v0.10.5
To support workload cluster 1.31, need to upgrade capi to 1.8.x To support workload cluster 1.30, need to upgrade capi to 1.7.x

[MCAPI-1] feat: upgrade capi & capo version

---

magnum_cluster_api/charts/k8s-keystone-auth/templates/secret-ca.yaml
magnum_cluster_api/resources.py

Fixes #434 
This is a simpler version of #435 which fixes the original intent of the keystone_auth CA cert handling.

keystone_auth: fix errors providing CA cert as string

---

magnum_cluster_api/driver.py
magnum_cluster_api/objects.py
magnum_cluster_api/resources.py

Since capo 0.11, v1alpha7 is deprecated.
This PR includes CRD changes from v1alpha7 to v1beta1.
Closes: https://github.com/vexxhost/magnum-cluster-api/issues/401

use v1beta1 CRD for capo resources

---

docs/user/labels.md
magnum_cluster_api/tests/unit/test_utils.py
magnum_cluster_api/utils.py

There are usecases when creation of load balancer monitors are required.
Let's add a corresponsive label to control behaviour of monitors
creation.
Default value is set in accordance with CCM.
[1] https://github.com/kubernetes/cloud-provider-openstack/blob/5ed0a04dc732d0e9bf70ddd3beaccdabd3841957/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md?plain=1#L231-L232

Add a label to control load-balancer monitor creation

---

magnum_cluster_api/resources.py

Previous fix [1] has brought a regression to the configuration, where
resulting YAML reffers to non-existent volume type on volume creation.
For instance, given that volume type is set to `default_encrypted`
resulting file will look like this:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: block-default-encrypted
uid: 70646c1f-369b-4e5c-b8be-66524120f721
resourceVersion: '430'
creationTimestamp: '2024-10-18T09:37:44Z'
annotations:
storageclass.kubernetes.io/is-default-class: 'true'
provisioner: cinder.csi.openstack.org
parameters:
type: default-encrypted
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
And then volume creation will fail with:
```
failed to provision volume with StorageClass "block-default-encrypted": rpc error: code = …
```

Do not convert volume_type name for StorageClass

---

hack/setup-capo.sh

motivation: bug fix for incorrect sg applying
ref: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.11.1

chore: upgrade capo version to 0.11.2

---

docs/user/labels.md
magnum_cluster_api/cmd/image_loader.py
magnum_cluster_api/manifests/calico/v3.25.2.yaml
magnum_cluster_api/manifests/calico/v3.26.5.yaml
magnum_cluster_api/manifests/calico/v3.27.4.yaml
magnum_cluster_api/manifests/calico/v3.28.2.yaml
magnum_cluster_api/manifests/calico/v3.29.0.yaml
magnum_cluster_api/tests/unit/cmd/test_image_loader.py

Starting with k8s 1.28 expected calico version is 3.28. While we should
dynamicially retrieve manifests for Calico, it needs slighly bigger
effort to implement if consider environments without Internet access.
Alternatively, image version can be templated in manifests, but there're
more changes to them happening from time to time, so still better to
use separate ones.
So as a workaround adding fresh calico manifests to the repo directly.

Add manifests for relevant calico versions

---

magnum_cluster_api/proxy/manager.py

When syncing kubeconfigs, we return if we aren't able to find a
secret which isn't right, since that can block the whole loop
of execution.

fix: continue, dont return in sync_kubeconfigs

---

magnum_cluster_api/driver.py
magnum_cluster_api/tests/unit/test_driver.py
pyproject.toml
src/addons/cloud_controller_manager.rs
uv.lock

If a MachineDeployment is missing, we end up not being able
to get rid of it with any way.  This patch changes the
exception to reraise the HTTPNotFound which will make Magnum
destroy the database object.
Closes: #639

fix: enable deleting missing machine deployment

---

magnum_cluster_api/resources.py

https://github.com/kubernetes-sigs/cluster-api/issues/12661
this is a pre-req change to upgrade CAPI to v1.10

set failureDomain as none instead of empty string

---

magnum_cluster_api/resources.py
src/features/admission_plugins.rs
src/features/mod.rs
src/resources.rs

Add support for enabling admission control plugins via the admission_control_list label on a cluster or cluster template. https://docs.openstack.org/magnum/latest/user/#admission-control-list

Add ability to set admission control plugins
